### PR TITLE
Updates faker Module/Class namespaces and fix deprecation errors

### LINKED ISSUE #608: Faker deprecations and some breaking changes
## User Story

Faker gem has deprecated some APIs. Looks like they have also changed namespaces and classes resulting on some deprecation messages and errors while running initial seed.

### 1. Breaking Changes
`Faker::SiliconValley` has moved to => `Faker::TvShows::SiliconValley`
* https://github.com/faker-ruby/faker/blob/master/doc/tv_shows/silicon_valley.md

Screen Shot 2019-09-10 at 7 27 31 PM

### 1. Deprecation warnings

```ruby
code_fund_ads/db/seeds.rb:284: Passing `name` with the 1st argument of `Internet.email` 
is deprecated. Use keyword argument like `Internet.email(name: ...)` 
instead
```

## Related

* https://github.com/faker-ruby/faker/issues/1576

### PR DESCRIPTION
**Pull request by dahal**
Closes #608

### CODE REVIEW

**Comment by dahal** [comment]
Sure, I did not get that specific error when seeding, i will try to reproduce it and update this PR. Thanks for the review. Also could you please review another PR about `user.invite!` when you get a chance? ( #610 )

@hopsoft

**Comment by dahal** [comment]
@hopsoft I managed to re-produce, at least on my end after `rake db:schema:load && IMPRESSIONS=10_000_000 rails db:seed` and i am sorta stuck on this error: are contributers expected to setup their own aws creds or can not use Disk for development storage.yml ?

```
local:
  service: Disk
```

**Comment by hopsoft** [comment]
🤔 Will get back to you in the AM on this.

**Comment by hopsoft** [comment]
Note that there is some overlap on this PR with #633 which should address the concerns raised here.

**Comment by hopsoft** [comment]
Thank you for pushing for this fix. Closing the PR as seeds have been *mostly* fixed by #633. Note that @cmckee-dev has some additional updates that will land in additional PRs.

**Pull request closed without merging**
