### PR TITLE
Update revenue percentage to 0.6

### PR DESCRIPTION
**Pull request by mglaman**
For https://github.com/gitcoinco/code_fund_ads/issues/441

### CODE REVIEW

**Comment by mglaman** [comment]
I ran `bin/rails db:migrate RAILS_ENV=test`

```
rails aborted!
NameError: uninitialized constant UpdatePropertyRevenuePercentage
bin/rails:9:in `<main>'

Caused by:
NameError: uninitialized constant UpdatePropertyRevenuePercentage
bin/rails:9:in `<main>'

Caused by:
NameError: uninitialized constant UpdatePropertyRevenuePercentage
bin/rails:9:in `<main>'

Caused by:
NameError: uninitialized constant UpdatePropertyRevenuePercentage
bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Need to review

**Comment by mglaman** [comment]
Fixed the migration constant. Not sure if `db/structure.sql` needs to be committed.

**Comment by coderberry** [comment]
@hopsoft do we need the db/structure.sql committed?

**Comment by mglaman** [comment]
I think it might need to be, for fresh installs. It was autogenerated/updated by some tool.

**Comment by hopsoft** [comment]
I'll regenerate after I merge this via `bin/generate_db_artifacts` so everything's clean.

**Pull request merged**
